# Generated by Django 3.1.4 on 2020-12-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janrlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr_adi', models.CharField(max_length=50, null=True, unique=True, verbose_name='Kitablarin janri')),
                ('qeyd_tarix', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar_adi', models.CharField(max_length=50, null=True)),
                ('yazar_soyadi', models.CharField(max_length=50, null=True)),
                ('qeyd_tarix', models.DateTimeField(auto_now_add=True)),
                ('yazar_janr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.janrlar')),
            ],
        ),
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitab_ad', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Kitab adi')),
                ('kitab_seh', models.IntegerField(default=0)),
                ('stokda', models.BooleanField(default=True, null=True)),
                ('kitab_janr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.janrlar')),
                ('kitab_yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.yazar')),
            ],
        ),
    ]
