# Generated by Django 3.1.4 on 2020-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kitab_qeyd_tarix'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitab',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
